"use client";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Stepper } from "@/components/ui/stepper";
import { usersAtom } from "@/lib/foundation-kit/atoms";
import axiosInstance from "@/lib/foundation-kit/axiosInstance";
import { zodResolver } from "@hookform/resolvers/zod";
import { atom, useAtom, useSetAtom } from "jotai";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { StepOne } from "./stepper/step-one";
import { StepThree } from "./stepper/step-three";
import { StepTwo } from "./stepper/step-two";
import { useQueryClient } from "@tanstack/react-query";

export const addUserAtom = atom({
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  autoGeneratedPassword: false,
  newPassword: "",
  currentPassword: "",
  institution: [],
  userGroup: [],
});

// Define base schema fields
const baseSchema = {
  firstName: z.string().min(2, {
    message: "First name must be at least 2 characters.",
  }),
  lastName: z.string().min(2, {
    message: "Last name must be at least 2 characters.",
  }),
  email: z.string().email({
    message: "Invalid email address.",
  }),
};

const addSchema = z
  .object({
    ...baseSchema,
    password: z.string().optional().nullable(),
    auto_generated_password: z.boolean().default(false),
  })
  .refine(
    (data) =>
      data.auto_generated_password ||
      (data.password && data.password.length >= 8),
    {
      message:
        "Either enter a password of at least 8 characters or enable auto-generated password.",
      path: ["password"],
    }
  );

// Schema for edit mode
const editSchema = z.object({
  ...baseSchema,
  newPassword: z
    .string()
    .min(8, {
      message: "New password must be at least 8 characters.",
    })
    .optional(),
  currentPassword: z
    .string()
    .min(8, {
      message: "Current password must be at least 8 characters.",
    })
    .optional(),
});

const createStepOneSchema = (mode) => {
  return mode === "add" ? addSchema : editSchema;
};

const UserDialog = ({ open, setOpen, mode = "add", userData = null }) => {
  const [currentStep, setCurrentStep] = useState(0);
  const [addUser, setAddUser] = useAtom(addUserAtom);
  const queryClient = useQueryClient();

  const stepOneForm = useForm({
    resolver: zodResolver(createStepOneSchema(mode)),
    defaultValues:
      mode === "add"
        ? {
            firstName: userData?.first_name || "",
            lastName: userData?.last_name || "",
            email: userData?.email || "",
            password: "",
            auto_generated_password: false,
          }
        : {
            firstName: userData?.first_name || "",
            lastName: userData?.last_name || "",
            email: userData?.email || "",
          },
  });

  const handleNext = async () => {
    if (currentStep === 0) {
      stepOneForm.handleSubmit((data) => {
        setAddUser({
          ...addUser,
          firstName: data.firstName,
          lastName: data.lastName,
          email: data.email,
          password: data.password,
          currentPassword: data.currentPassword,
          newPassword: data.newPassword,
          autoGeneratedPassword: data.auto_generated_password,
        });
        setCurrentStep(currentStep + 1);
      })();
    } else if (currentStep === 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleFinish = async () => {
    if (currentStep === 0) {
      stepOneForm.handleSubmit(async (data) => {
        setAddUser({
          ...addUser,
          firstName: data.firstName,
          lastName: data.lastName,
          email: data.email,
          password: data.password,
          currentPassword: data.currentPassword,
          newPassword: data.newPassword,
          autoGeneratedPassword: data.auto_generated_password,
        });
        try {
          const addUserPayload = {
            first_name: data.firstName,
            last_name: data.lastName,
            email: data.email,
            password: data.password,
            auto_generated_password: data.auto_generated_password,
            is_active: true,
          };
          const editUserPayload = {
            first_name: data.firstName,
            last_name: data.lastName,
            email: data.email,
            is_active: true,
          };
          if (data.currentPassword) {
            editUserPayload.password_update = {
              current_password: data.currentPassword,
              new_password: data.newPassword,
            };
          }

          if (mode === "add") {
            const response = await axiosInstance.post(
              "/auth/register",
              addUserPayload
            );
          } else {
            const response = await axiosInstance.patch(
              `/auth/users/${userData.id}`,
              editUserPayload
            );
          }

          toast.success(
            mode === "add"
              ? "User created successfully"
              : "User updated successfully"
          );
          setOpen(false);

          queryClient.invalidateQueries({
            queryKey: ["users"],
            refetchType: "active",
          });

          stepOneForm.reset();
          setAddUser({
            firstName: "",
            lastName: "",
            email: "",
            institution: [],
            userGroup: [],
          });
          setCurrentStep(0);
        } catch (error) {
          toast.error(error?.response?.data?.detail || "Error creating user");
        }
      })();
    }
    if (currentStep === 1 || currentStep === 2) {
      try {
        const addUserPayload = {
          first_name: addUser.firstName,
          last_name: addUser.lastName,
          email: addUser.email,
          password: addUser.password,
          institutions: addUser.institution,
          roles: addUser.userGroup,
          auto_generated_password: addUser.autoGeneratedPassword,
          is_active: true,
        };
        const editUserPayload = {
          first_name: addUser.firstName,
          last_name: addUser.lastName,
          email: addUser.email,
          institutions: addUser.institution,
          roles: addUser.userGroup,
          is_active: true,
        };
        if (addUser.currentPassword) {
          editUserPayload.password_update = {
            current_password: addUser.currentPassword,
            new_password: addUser.newPassword,
          };
        }

        if (mode === "add") {
          const response = await axiosInstance.post(
            "/auth/register",
            addUserPayload
          );
        } else {
          const response = await axiosInstance.patch(
            `/auth/users/${userData.id}`,
            editUserPayload
          );
        }

        toast.success(
          mode === "add"
            ? "User created successfully"
            : "User updated successfully"
        );
        setOpen(false);

        queryClient.invalidateQueries({
          queryKey: ["users"],
          refetchType: "active",
        });

        stepOneForm.reset();
        setAddUser({
          firstName: "",
          lastName: "",
          email: "",
          institution: [],
          userGroup: [],
        });
        setCurrentStep(0);
      } catch (error) {
        toast.error(error?.response?.data?.detail || "Error creating user");
      }
    }
  };

  const steps = [
    {
      title: "Step 1",
      description: mode === "add" ? "Add user details" : "Edit user details",
      component: <StepOne form={stepOneForm} mode={mode} />,
    },
    {
      title: "Step 2",
      description: "Select institutions",
      component: <StepTwo userData={userData} mode={mode} />,
    },
    {
      title: "Step 3",
      description: "Select user groups",
      component: <StepThree userData={userData} mode={mode} />,
    },
  ];

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-[550px] max-h-[500px] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{mode === "add" ? "Add User" : "Edit User"}</DialogTitle>
          <DialogDescription>
            {mode === "add"
              ? "Add a new user to the system."
              : "Edit existing user details."}
          </DialogDescription>
        </DialogHeader>
        <div className="container mx-auto py-2">
          <Stepper
            steps={steps}
            currentStep={currentStep}
            onStepChange={setCurrentStep}
            onNext={handleNext}
            onFinish={handleFinish}
          >
            <div className="mt-8 p-4 border rounded-md">
              <h2 className="text-lg font-semibold mb-2">
                {steps[currentStep].component}
              </h2>
            </div>
          </Stepper>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default UserDialog;
